### ISSUE TITLE
Improve MAC Address support

### ISSUE THREAD

**Issue by mike4263** [RedHatOfficial/odie#18]
The provision_vm role and dnsmasq_configuration how have some redundant variables defining the the jumphost mac address.   Need to investigate a more reliable way to determine the jumphosts mac address. 

For an example, the default hostname `jumphost01.lab.odie` will return a mac address: `52:54:00:0d:10:f1`

To break that down:

- `52:54:00` is defined by the `mac_prefix` variable.  This is the prefix for KVM NICs
* `0d:1` is product placement
- the `0` is the `cluster_id` allowing you to spin up additional clusters.  Define this as a hostvar in the hosts.csv to prevent from clobbering this (which is what I always end up doing..)
- The `f` is derived from the dictionary below where the key is the "flavor" of the VM defined in hosts.csv
- The `1` is the last digit of the first section of the hostname (aka `jumphost01` is `1`).  If your hostnames don't end in a valid hex character (0-F), this will break.

Here is all the logic that does this:

```
mac_prefix: "52:54:00:0d:1"
cluster_id: "0" # Increment this for each additional cluster
mac_suffix: "{{ mac_flavor_decoder[hostvars[hostname].flavor] }}{{ hostname.split('.')[0][-1] }}"
mac_address: "{{mac_prefix}}{{cluster_id}}:{{mac_suffix}}"

mac_flavor_decoder:
  node: 'a'
  master: 'b'
  infra: 'c'
  registry: 'd'
  lb_nfs: 'e'
  jumphost: 'f'
```

Of course, you can always just define complete addresses via `mac_address` or just override the individual components as necessary.
